### PR TITLE
Added the very simple yalz77 compressor.

### PR DESCRIPTION
**Pull request by ivan-tkatchev**
Hi. I've added my very simple and very naive (designed to be easy to understand and robust to use) LZ77 compressor to squash. I think it would be interesting to compare it to less naive implementations.

Thank you.

### CODE REVIEW

**Comment by nemequ** [comment]
Wow, very good work.  You even udated `docs/index.md`—I regularly forget to do that.  Just two (very minor) things:

# Please use a git submodule instead of copying the sources over.  I'm not concerned about the file size or anything, it's just really nice to be able to update all the submodules to pull in new versions.
# Please change the blocksize and searchlen options to block-length and search-length, just to fit with the style of other plugins (e.g., bsc and lz4 already have "block-size" options).

**Comment by ivan-tkatchev** [comment]
Done and done. Thank you.

**Comment by nemequ** [comment]
Thanks!  Merged as https://github.com/nemequ/squash-corpus/issues (I squashed it into a single commit just to keep the noise down).

It should show up in the bechmark in about a week (the first run is actually still in progress on some of the slower machines!).  If you want I can send you a note when that happens?

**Comment by ivan-tkatchev** [comment]
It's OK, I'll check up on it myself. :)

**Pull request closed without merging**
