### PR TITLE
Fixed yalz77 crashing bugs.

### PR DESCRIPTION
**Pull request by ivan-tkatchev**
Fixed the crashing bugs in yalz77 you so kindly sent me via email. Should experience no crashing or hanging on random data now.

P.S. I've removed the SQUASH_BUFFER_FULL return code in the process, but since yalz77 dynamically allocates output buffers this return code probably doesn't make sense anyways.

Thank you.

### CODE REVIEW

**Comment by nemequ** [comment]
> P.S. I've removed the SQUASH_BUFFER_FULL return code in the process, but since yalz77 dynamically allocates output buffers this return code probably doesn't make sense anyways.

I'm guessing this is why Travis is complaining.  yalz77 may allocate space dynamically, but it is then copied into a buffer supplied to the user, which may not have enough space.  There are unit tests for decompressing to a buffer which is known to be too small, the crash is probably most likely there.

**Comment by nemequ** [comment]
Also, you might want to revert dfb81cbd7108af47bf976f972d0ceffd3e343374 while you are at it.  If you fixed the hangs that test should work now, too.

**Comment by ivan-tkatchev** [comment]
OK, I've fixed the buffer test and brought back SQUASH_BUFFER_FULL and reverted dfb81cb. Thanks.

**Comment by nemequ** [comment]
Eh, sorry, bad timing on that forced update causing a conflict for you.  I thought it would be okay since it was only in place for 5 minutes…  I guess I need to stop doing that.

Looks good, passes all tests and the benchmark.  Marged, thanks :)

**Pull request merged**
