### PR TITLE
Update brotli

### PR DESCRIPTION
**Pull request by eustas**
Use new brotli decoder API
Add "can flush" flag and support "hard flush" in streaming encoder

### CODE REVIEW

**Comment by nemequ** [comment]
Thanks for this :)

It looks like the buffer unit test fails with this (Travis reports a success, but if you look at the log it fails… I'll look into that right now).

The problem seems to be that `BrotliDecompressBuffer` now returns `BROTLI_RESULT_ERROR` if the destination buffer is too small instead of `BROTLI_RESULT_NEEDS_MORE_OUTPUT`.  Would it be possible to fix that?

**Comment by eustas** [comment]
Oh, currently I'm on my way home. I'll take a look at it this evening.

**Comment by nemequ** [comment]
No rush.  If you rebase both Travis and AppVeyor should be working as expected now, sorry for the inconvenience.

**Comment by nemequ** [comment]
Merged, thanks.  Sorry about the delay, GitHub doesn't notify automatically when PRs are updated and I forgot to check this.

I'm a bit surprised by the workaround for the buffer full issue…  I expected a patch in Brotli to bring back the old behavior of returning `BROTLI_RESULT_NEEDS_MORE_OUTPUT`.  Is there a reason you didn't want to do that?  It can actually be useful to know that decompression failed as a result of insufficient space in the buffer…

The reason I have a test to make sure plugins return `SQUASH_BUFFER_FULL` is that, for codecs which don't store the uncompressed length in the buffer, it can be hard to know how much space to allocate for decompression unless that information is stored out-of-band.  Returning an error code specific to that situation allows the user to allocate a larger buffer and try again, but doing that generic error code could cause an endless loop if the data is corrupted.

**Comment by eustas** [comment]
Hello.
In last brotli decode update we've changed BrotliDecompressBuffer to act more in "all-or-nothing" manner - i.e. return either success or failure, but not "to-be-continued" results.
Currently we have bunch of deprecated API, and outdated documentation. As soon as deprecated API is removed I'll carefully update documentation and clarify all possible outcomes and recommended scenarios of usage.

**Pull request closed without merging**
