### PR TITLE
Testing gcc5 warning

### PR DESCRIPTION
**Pull request by jibsen**
This PR is just to get travis to build while I play around with it.

### CODE REVIEW

**Comment by jibsen** [comment]
It looks like the warning goes away when compiling without LTO. Perhaps it is a GCC issue.

**Comment by jibsen** [comment]
Could be related to [this GCC bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61886), although it also appears at `_FORTIFY_SOURCE=1`.

**Comment by jibsen** [comment]
Without `_FORTIFY_SOURCE`, squash itself compiles, but the build fails later at a plugin. So it seems the combination of `_FORTIFY_SOURCE > 0` and LTO causes this.

**Comment by nemequ** [comment]
Wow, thanks for looking into this.  With the information provided I've been able to narrow this down to a simple test case which reproduces the issue on Fedora 23 (though not on Fedora 22, and both use GCC 5.1):

```c
/* Compile with -D_FORTIFY_SOURCE=1 -O1 -flto */

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <assert.h>

#define BUF_SIZE ((size_t) 1024)
#define LIKELY(expr) (__builtin_expect ((expr), true))
#define UNLIKELY(expr) (__builtin_expect ((expr), false))

int main(int argc, char *argv[]) {
  int res = EXIT_SUCCESS;
  uint8_t* data = malloc (BUF_SIZE);
  size_t size, remaining, data_size;
  FILE* fp_in = fopen ("/dev/stdin", "r");

  if (argv[1] == NULL) {
    fprintf (stderr, "You must provide a length\n");
    res = EXIT_FAILURE;
    goto cleanup;
  }
  remaining = size = (size_t) atoi (argv[1]);
  assert (size > 1);

  assert (data != NULL);

  while (remaining != 0) {
    const size_t req_size = (remaining > BUF_SIZE) ? BUF_SIZE : remaining;

    /* In function ‘__fread_unlocked_alias’, */
    /*   inlined from ‘main’ at g.c:38:15: */
    /* /usr/include/bits/stdio2.h:351:9: warning: call to ‘__fread_unlocked_chk_warn’ declared with attribute warning: fread_unlocked called with bigger size * nmemb than length of destination buffer */
    /*   return __fread_unlocked_chk (__ptr, __bos0 (__ptr), __size, __n, */
    /*          ^ */
    data_size = fread_unlocked (data, 1, req_size, fp_in);
    if (data_size == 0) {
      res = LIKELY(feof (fp_in)) ? EXIT_SUCCESS : EXIT_FAILURE;
      goto cleanup;
    }

    remaining -= req_size;
    fprintf (stderr, "%s:%d: read %4zu of %4zu total bytes, %4zu remaining\n", __FILE__, __LINE__, data_size, size, remaining);
  }

 cleanup:
  free (data);
  fclose (fp_in);

  return res;
}
```

You're right, the combination of _FORTIFY_SOURCE and LTO triggers it.  I'm not sure whether the issue is in glibc or gcc, but I'll try to figure it out.  In the meantime, I've re-enabled the gcc-5 release build but taken out _FORTIFY_SOURCE until this is resolved.

**Pull request closed without merging**
