### PR TITLE
Use native brotli streaming support for compression

### PR DESCRIPTION
**Pull request by eustas**

### CODE REVIEW

**Comment by nemequ** [comment]
I don't think this will work for files larger than the block size (in other words, when [`squash_stream_yield`](https://quixdb.github.io/squash/api/c/group__SquashStream.html#ga426ecde6b4f4a6a399fa5ee5be24026f) is called.  That function must only be called from a thread-based plugin, which Brotli currently isn't.  If you add [`SQUASH_CODEC_INFO_RUN_IN_THREAD`](https://quixdb.github.io/squash/api/c/group__SquashCodec.html#ggabdbf4a0f26de22f53d71d940fb6a2e9ea8340c1f0c1fe7f490d1e06f91247b044) to the codec info then this would become a thread-based plugin and yielding should work.

That said, I don't think that is a good idea.  Thread-based plugins work by spawning a thread to perform the processing.  When the user calls `squash_stream_process` control switches from the main thread to the processing thread that Squash spawned; once all the information in the buffers has been processed `squash_stream_yield` is called to switch control back to the main thread, and the cycle repeats until processing has completed.

This allows us to work with APIs which expect to be provided with callbacks which pull in data as opposed to APIs which will let you process data piece by piece, but the threading bits will decrease performance so it's better to avoid it if possible.  Unless there are some real benefits to switching the callback-based API it's probably a mistake.

The other patch ("Use buffers size matching to compressor block size.") seems good, I'll take a closer look in a couple hours and merge it.

**Comment by nemequ** [comment]
I cherry picked 3f13042e24623f1eb579aa8cdaefd758b09f8fc1 (as d158ffaef2af0d7d0a5e0e803ad254c6affd08a3).

Let me know how you feel about switching to the thread-based version.  Based on your e-mail address I'm guessing you have some affiliation to brotli's development and, if so, I'm willing to do pretty much whatever you want with the plugin; if you aren't comfortable with people using the APIs I did we can use your patch to switch over to the thread-based interface, but I'm pretty sure there will be a performance hit.  Otherwise, unless I'm missing something I think we can close this PR.

**Comment by eustas** [comment]
Actually, brotli plugin works as threaded now: I've just copy-pasted code with squash_stream_yield from squash_brotli... That is why CPU is bigger than wall time.
I'll examine what could be done about this.
Thank you for your support.

**Comment by nemequ** [comment]
Ah, okay.  I think most of the hit would come from data not being in the (right) cache on the CPU, but if Brotli is already taking that hit I doubt there would be a significant change if we added another thread in Squash.

I just noticed that Brotli already has RUN_IN_THREAD in its flags (it shouldn't, that's a bug), so that explains why your patch worked.  All it is really doing right now is adding the overhead of spawning the thread for no benefit, so if you don't want to go that route we should remove it.

If you want I can run the benchmark against both versions and see how they compare (or you can, just remove that flag before you run the current version).

**Comment by nemequ** [comment]
Okay, I misunderstood your comment.  I thought you meant brotli itself was threaded, not the plugin.  In that case I think your patch is acceptable—I'll run some tests tonight, and merge it if all goes well.  Sorry about all the confusion :(

**Comment by nemequ** [comment]
Pushed.  Thanks for the patches, and sorry again about the confusion.

**Pull request closed without merging**
