### PR TITLE
Fix #228

### LINKED ISSUE #228: cmake: zlib-ng check failure
Currently trying to build squash with just my system libs and while most libraries seem to be incorrectly enabled, perhaps requiring that I manually `--disable-` each one I don't have, zlib-ng still seems to be causing issues:

```
% ./configure --prefix=/usr --disable-zlib-ng --disable-brieflz --disable-brotli
-- Found CppCheck: /usr/bin/cppcheck (found version "1.79") 
-- bsc plugin: enabled
-- bzip2 plugin: using external library
-- copy plugin: enabled
-- crush plugin: enabled
-- csc plugin: disabled
-- density plugin: disabled
-- doboz plugin: disabled
-- fari plugin: enabled
-- Could NOT find FASTLZ (missing:  FASTLZ_INCLUDE_DIR FASTLZ_LIBRARIES) 
-- fastlz plugin: enabled
-- gipfeli plugin: enabled
-- heatshrink plugin: enabled
-- libdeflate plugin: enabled
-- Checking for module 'liblz4'
--   Found liblz4, version 1.7.5
-- lz4 plugin: using external library
-- Checking for module 'liblzf'
--   Package 'liblzf', required by 'virtual:world', not found
-- lzf plugin: enabled
-- lzfse plugin: enabled
-- lzg plugin: enabled
-- lzham plugin: enabled
-- lzjb plugin: enabled
-- lzma plugin: using external library
-- lzo plugin: using external library
-- miniz plugin: enabled
-- ms-compress plugin: enabled
-- ncompress plugin: enabled
-- quicklz plugin: enabled
-- snappy plugin: using external library
-- wflz plugin: enabled
-- yalz77 plugin: enabled
-- zlib plugin: using external library
CMake Error at plugins/zlib-ng/CMakeLists.txt:6 (file):
  file failed to open for reading (No such file or directory):

    /home/earnest/build/pkgbuilds/squash-git/src/squash/plugins/zlib-ng/zlib-ng/zconf.h.in
Call Stack (most recent call first):
  plugins/zlib-ng/CMakeLists.txt:11 (generate_cmakein)


CMake Error: File /home/earnest/build/pkgbuilds/squash-git/src/squash/plugins/zlib-ng/zconf.h.cmakein does not exist.
CMake Error at plugins/zlib-ng/CMakeLists.txt:13 (configure_file):
  configure_file Problem configuring file


-- zlib-ng plugin: disabled
-- zling plugin: enabled
-- Could NOT find ZPAQ (missing:  ZPAQ_INCLUDE_DIR ZPAQ_LIBRARIES) 
-- zpaq plugin: enabled
-- Checking for module 'libzstd'
--   Found libzstd, version 1.1.4
-- zstd plugin: using external library
-- Configuring incomplete, errors occurred!
See also "/home/earnest/build/pkgbuilds/squash-git/src/squash/CMakeFiles/CMakeOutput.log".
See also "/home/earnest/build/pkgbuilds/squash-git/src/squash/CMakeFiles/CMakeError.log".
```

### PR DESCRIPTION
**Pull request by Cloudef**
This makes it possible to build squash if plugin submodules are not cloned and disabled.
Also fixed lzma builds.

### CODE REVIEW

**Comment by Cloudef** [comment]
This will actually break brotli and brieflz. Need to refactor a bit.

**Comment by Cloudef** [comment]
Now both cases, system and embed should work. Also fixed brotli pkg names which upstream broke backwards compatibility for.

**Comment by nemequ** [comment]
Sorry about taking so long to review this--I've been busy lately.

The changes are acceptable in principle, but this causes [the build](https://travis-ci.org/quixdb/squash/builds/295086552) to fail due to a missing header. If you don't want to try to fix that I'll try to take a look soon…

**Comment by Cloudef** [comment]
Thank's I'll take a look.

**Comment by Cloudef** [comment]
All the embedded plugins seemed to build on the OSX I'm currently on. I don't think I can trigger the travis job so can't confirm there. Anyhow I noticed the order of things for the stuff I added in SquashPlugin.cmake was bit wrong.

**Comment by nemequ** [comment]
That did the trick. Rebased and merged, thanks :)

Our Travis setup is a bit odd due to wanting to test everything before pushing to master, but not wanting to rebuild a commit once it's pushed to master. If you file a PR targeting a branch other than master it should work :/

**Pull request closed without merging**
