### PR TITLE
Rewrite brotli plugin to work with synchronous streams.

### PR DESCRIPTION
**Pull request by eustas**
* rewrite brotli plugin to work with synchronous streams
* update brotli to the latest version (contains important fix)
* fix max_compressed_size function

### CODE REVIEW

**Comment by nemequ** [comment]
I'm happy to merge after this passes all the unit tests.  Looks like it is failing `flush` and `stream-single-byte` (it's not just Travis, I'm reproducing the failures on my laptop, too).  During development, you can run them with `SQUASH_PLUGINS=../plugins ./flush-or-stream-single-byte brotli` to avoid checking all the other plugins, too.

Also, could you please add yourself to the copyright for the file?  I think it's past time.

**Comment by eustas** [comment]
Looks like brotli decoder doesn't support flush... It is forced to dump its internal buffer only when last block is finished. I'm going to update brotli decoder to flush output after each block tomorrow...

**Comment by eustas** [comment]
Making brotli decoder flush-friendly would take few weeks. So, I've removed CAN_FLUSH flag for now.

**Comment by nemequ** [comment]
Nice, thanks!

Do you want me to file an issue against Brotli to track support for flushing in the decoder?

**Comment by eustas** [comment]
Yes, it would be nice and motivating =)

**Pull request merged**
